---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nodejs-ex-app-dev-build
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/karthikjeeyar/demo-nodejs-ex-gitops.git
    targetRevision: HEAD
    path: ./helm/build
    helm:
      valueFiles:
        - Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-nodejs-ex-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m